### ISSUE TITLE
making an error in the credentials file does not generate an exception

### ISSUE THREAD

**Issue by cookie33** [EUDAT-B2SAFE/B2HANDLE#110]
Hi,

When having the following credentials file:

```
{
    "handle_server_url": "https://fqdn8001",
    "private_key": "/home/.../355_841_privkey.pem",
    "certificate_only": "/home/.../355_841_certificate_only.pem",
    "prefix": "841",
    "handleowner": "200:0.NA/841",
    "reverselookup_username": "841",
    "reverselookup_password": "<password>",
    "HTTPS_verify": "True"
    "HTTPs_verify": "True"
}
```
It misses one `,` after HTTPS_verify

It does not create the expected exception:
```
./epicclient2.py os /home/.../epic2_credentials create www.test.com
Traceback (most recent call last):
  File "./epicclient2.py", line 377, in <module>
    _ARGS.func(_ARGS)
  File "./epicclient2.py", line 120, in create
    credentials = PIDClientCredentials.load_from_JSON(args.credpath)
  File "/usr/lib/python2.6/site-packages/b2handle/clientcredentials.py", line 54, in load_from_JSON
    jsonfilecontent = json.loads(open(json_filename, 'r').read())
  File "/usr/lib64/python2.6/json/__init__.py", line 307, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.6/json/decoder.py", line 319, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.6/json/decoder.py", line 336, in raw_decode
    obj, end = self._scanner.iterscan(s, **kw).next()
  File "/usr/lib64/python2.6/json/scanner.py", line 55, in iterscan
    rval, next_pos = action(m, context)
  File "/usr/lib64/python2.6/json/decoder.py", line 193, in JSONObject
    raise ValueError(errmsg("Expecting , delimiter", s, end - 1))
ValueError: Expecting , delimiter: line 10 column 5 (char 373)
```
I expected `CredentialsFormatError` and NOT the value error.

**Comment by cookie33** [comment]
It now raises a `CredentialsFormatError` as follows:
```
$ ./epicclient2.py os /home/.../epic2_credentials create www.test.com
/usr/lib/python2.6/site-packages/b2handle/clientcredentials.py:56: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
  raise CredentialsFormatError(msg="Invalid JSON syntax: "+exc.message)
error
```

But I am wondering if this is the correct output. I have never seen this error before:
```
/usr/lib/python2.6/site-packages/b2handle/clientcredentials.py:56: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
```

If we generate an other error specific with the handle protocol it shows:
```
$ ./epicclient2.py os /home/.../epic2_credentials create www.test.com
Traceback (most recent call last):
  File "./epicclient2.py", line 401, in <module>
    _ARGS.func(_ARGS)
  File "./epicclient2.py", line 176, in create
    **extype)
  File "/usr/lib/python2.6/site-packages/b2handle/handleclient.py", line 845, in register_handle
    handlerecord_json = self.retrieve_handle_record_json(handle)
  File "/usr/lib/python2.6/site-packages/b2handle/handleclient.py", line 292, in retrieve_handle_record_json
    response=response
b2handle.handleexceptions.GenericHandleError: Error during interaction with Handle Server (retrieving).
        Handle: 84A/7fcb4114-bdf5-11e6-ad68-5254000df0ed
        URL: https://fqdn:8001/api/handles/84A/7fcb4114-bdf5-11e6-ad68-5254000df0ed
        HTTP Status Code: 400
        Response: {"responseCode":301,"message":"That prefix doesn't live here","handle":"84A/7fcb4114-bdf5-11e6-ad68-5254000df0ed"}
```
Here the error is also shown.

**Comment by cookie33** [comment]
If the `clientcredentials.py` line 56 is changed to
```
  raise CredentialsFormatError(msg="Invalid JSON syntax: "+str(exc))
```
The error/warning is gone.

**Comment by cookie33** [comment]
Fixed in devel branch. Will be fixed in release when devel is merged to master branch.
