### ISSUE TITLE
HTTPS_verify could be a string, ca_cert path

### ISSUE THREAD

**Issue by javaguirre** [EUDAT-B2SAFE/B2HANDLE#55]
Hi!

I want to pass a ca_cert in `HTTPS_verify` so the *requests* library uses It for SSL verification ([documentation](http://docs.python-requests.org/en/master/user/advanced/#ssl-cert-verification)).

Right now is not possible because boolean is being forced as a type for HTTPS_verify.

```python
Traceback (most recent call last):
  File "epicclient2.py", line 297, in <module>
    _ARGS.func(_ARGS)
  File "epicclient2.py", line 117, in create
    **extra_config)
  File "/usr/lib/python2.7/site-packages/b2handle-1.0-py2.7.egg/b2handle/handleclient.py", line 261, in instantiate_with_credentials
    **additional_config
  File "/usr/lib/python2.7/site-packages/b2handle-1.0-py2.7.egg/b2handle/handleclient.py", line 109, in __init__
    self.__handlesystemconnector = HandleSystemConnector(handleclient=self, **args)
  File "/usr/lib/python2.7/site-packages/b2handle-1.0-py2.7.egg/b2handle/handlesystemconnector.py", line 83, in __init__
    self.__store_args_or_set_to_defaults(args, defaults)
  File "/usr/lib/python2.7/site-packages/b2handle-1.0-py2.7.egg/b2handle/handlesystemconnector.py", line 117, in __store_args_or_set_to_defaults
    self.__HTTPS_verify = util.string_to_bool(args['HTTPS_verify'])
  File "/usr/lib/python2.7/site-packages/b2handle-1.0-py2.7.egg/b2handle/util.py", line 93, in string_to_bool
    return dic[string.lower()]
KeyError: u'ca_cert.crt'
```

**Comment by TobiasWeigel** [comment]
+1

I've had a look at the code and the requests library and think this is a fair request. I do not see a reason why the verify option should be restricted to bool only - requests library allows such usage (which I also just learned :-)).

**Comment by javaguirre** [comment]
I'd like to prepare a PR with this functionality.

On Thu, Apr 7, 2016, 16:12 TobiasWeigel <notifications@github.com> wrote:

> +1
>
> I've had a look at the code and the requests library and think this is a
> fair request. I do not see a reason why the verify option should be
> restricted to bool only - requests library allows such usage (which I also
> just learned :-)).
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/EUDAT-B2SAFE/B2HANDLE/issues/55#issuecomment-206925032>
>
-- 
—
Javier Aguirre
https://javaguirre.net

**Comment by TobiasWeigel** [comment]
By all means, please do. :-) It should also still go into v1.0.1 immediately; I don't expect test failure.

**Comment by javaguirre** [comment]
Merged
